#!/usr/local/bin/bash

SERVERS=$(curl --silent https://nordvpn.com/api/server/stats)

# Reset in case getopts has been used previously in the shell.
OPTIND=1

location="" # An empty strings matches all possible locations
capacity=70 # Default capacity value is 70%

while getopts ":l:c:h" opt; do
    case "$opt" in
    h)
      show_help
      exit 0
      ;;
    l)
      location=$OPTARG >&2
      ;;
    c)
      capacity=$OPTARG >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument."
      echo "Use -h to show help." >&2
      exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      echo "Use -h to show help." >&2
      exit 1
      ;;
    esac
done

echo "Looking for servers in ${location^^} with current capacity higher than $capacity%..."

jq --compact-output -r --arg location $location --arg capacity $capacity \
  '[. | to_entries[] | {server: .key, capacity: .value.percent} | select(.capacity > ($capacity|tonumber)) | select(.server | contains($location))] | sort_by(-.capacity) | .[]' \
  <<<"$SERVERS"
